name: Docker Image ARM

on:
  push:
    branches: [ "ragflow" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Install Tools
      run: brew update && brew install uv
    - name: Change Project
      run: sed -i '' 's/xgboost==1.5.0/xgboost==1.6.0/g' pyproject.toml
    - name: Install Dependency
      run: uv run download_deps.py

    - name: Build Image
      run: docker build -f Dockerfile.deps -t infiniflow/ragflow_deps .

    - name: DockerHub Login
      uses: docker/login-action@v3.0.0
      with:
        username: miaojun
        password: ${{ secrets.DOCKERHUB_PWD }}

    - name: Build Dependency
      run: docker build -f Dockerfile.deps -t infiniflow/ragflow_deps .

    - name: Set Docker Tag
      run: echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -f Dockerfile -t miaojun/ragflow:${{ env.IMAGE_TAG }} .

    - name: Push Image
      run: docker push miaojun/ragflow:${{ env.IMAGE_TAG }}
