name: Docker Image ARM

on:
  push:
    branches: [ "ragflow" ]

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Install uv
      run: |
        curl -L https://github.com/astral-sh/uv/releases/latest/download/uv-aarch64-unknown-linux-gnu.tar.gz -o uv.tar.gz
        tar -xzf uv.tar.gz
        sudo install uv /usr/local/bin/uv
        uv --version
    - name: Change Project
      run: sed -i 's/xgboost==1.5.0/xgboost==1.6.0/g' pyproject.toml
    - name: Install Dependency
      run: uv run download_deps.py

    - name: Build Image
      run: docker build -f Dockerfile.deps -t infiniflow/ragflow_deps .

    - name: DockerHub Login
      uses: docker/login-action@v3.0.0
      with:
        username: miaojun
        password: ${{ secrets.DOCKERHUB_PWD }}

    - name: Build Dependency
      run: docker build -f Dockerfile.deps -t infiniflow/ragflow_deps .

    - name: Set Docker Tag
      run: echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -f Dockerfile -t miaojun/ragflow:${{ env.IMAGE_TAG }} .

    - name: Push Image
      run: docker push miaojun/ragflow:${{ env.IMAGE_TAG }}
