name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: DockerHub Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build Docker image    
      run: docker build . --file Dockerfile --tag miaojun/ubuntu:tools-22.04
    - name: Push Image
      run: docker push miaojun/ubuntu:tools-22.04
