name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: DockerHub Login
      uses: docker/login-action@v3.0.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.REGISRRY_USERNAME }}
        password: ${{ secrets.REGISRRY_PASSWORD }}
    - name: Build Docker image    
      run: docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/mj-mirror/mypython:0519
    - name: Push Image
      run: docker push registry.cn-hangzhou.aliyuncs.com/mj-mirror/mypython:0519
